### ISSUE TITLE
Is this a real project

### ISSUE THREAD

**Issue by Slyker** [fusorjs/dom#1]
Hi buddy,
I wanted to know if this is a real project I thought about a tailwind theming system that allows define layout classes. Do you think we can use such a system so it updates element’s classes when theme changed ?

**Comment by isumix** [comment]
Yes, it is real.
Sure you can use it to update classes dynamically.
Here is a simple snippet:

```jsx
let toggle = false;

const getClassName = () => (toggle ? "on" : "off");
const handleClick = () => {
  toggle = !toggle;
  wrapper.update();
};

const wrapper = (
  <section>
    <h1 class={getClassName}>Fusor Switch Classes</h1>
    <button click$e={handleClick}>Toggle Class</button>
  </section>
);

document.body.append(wrapper.element);
```

Here is a full example: <https://codesandbox.io/s/fusor-switch-classes-fqr79k?file=/src/index.tsx>

You could also use something like <https://github.com/lukeed/clsx> to make life easier.
